### PR TITLE
fix #353

### LINKED ISSUE #353: index.js should not point to `src`
index.js should never point to the src of gymnast. Instead it should point to a babel-ified version of the src that does not use es6 imports. Otherwise, users need to do all transpilation of gymnast themselves.

Looks like we can just point to `gymnast/dist/gymnast.js`?

### PR DESCRIPTION
**Pull request by arahansen**

### CODE REVIEW

**Comment by arahansen** [comment]
I recall this was originally put in place to match Fleets needs. Should this still cover their use case?

**Comment by obartra** [comment]
I added this after you requested the default version not to be the dist (to use the uncompiled version). Ideally we would point to a transpiled but unbuilt version as it is now we should move all dependencies to dev dependencies

**Comment by arahansen** [comment]
we still dependencies to stay as dependencies for flow types to work properly

**Comment by obartra** [comment]
oh got it, I thought flow types were installed and checked for dev dependencies as well. Either way I think this is good to go, we can tackle the deps later if we need to

**Pull request merged**
