### PR TITLE
Next

### PR DESCRIPTION
**Pull request by obartra**
Next iteration of gymnast

### Pre Release

- [x] Remove Layout, Root, asCol, asLayout
- [x] Remove Layout, Root, asCol, asLayout from examples
- [x] Reduce bundle size and bundle size threshold
- [x] Cleanup CircleCI yaml file
- [x] Stabilize branch / pass CI
- [x] Use React.forwardRef instead of relying on `innerRef` https://github.com/gymnastjs/gymnast/pull/407
- [x] Switch to react hooks https://github.com/gymnastjs/gymnast/pull/407
- [x] Switch to TS https://github.com/gymnastjs/gymnast/pull/407
- [x] Update dependencies (except nightwatch) https://github.com/gymnastjs/gymnast/pull/409
- [x] Add support for flex-direction `row` and `column` https://github.com/gymnastjs/gymnast/pull/410
- [x] switch top / bottom / right / left to "start" and "end" https://github.com/gymnastjs/gymnast/pull/410
- [x] Add `Col` and `Grid` specific tests https://github.com/gymnastjs/gymnast/pull/411
- [x] Remove setting fallback key through context https://github.com/gymnastjs/gymnast/pull/411
- [x] Rename `ConfigProvider` to `GymnastProvider` https://github.com/gymnastjs/gymnast/pull/411
- [x] Document reduced react tree on migration guide https://github.com/gymnastjs/gymnast/pull/412
- [x] Publish TS types https://github.com/gymnastjs/gymnast/pull/413, https://github.com/gymnastjs/gymnast/pull/414, https://github.com/gymnastjs/gymnast/pull/415
- [x] Publish next as npm `@next` (manually released)
- [x] Remove flow types

### Post Release

- [x] Validate TS types https://github.com/gymnastjs/gymnast/pull/414, https://github.com/gymnastjs/gymnast/pull/415
- [x] Validate re-render inconsistencies on resolution changes fix

### Before Master Release

- [x] Update `package.json#publishConfig` 
- [x] Revert `package.json#version`
- [x] Update default branch on https://gymnast.readme.io
- [ ] Update README / code sandbox demo
- [x] Run semantic release dry run to ensure correct versioning

BREAKING CHANGES

### CODE REVIEW

**Comment by obartra** [comment]
`<Col />` cannot be easily removed since it's used by other projects

**Comment by arahansen** [comment]
next next: React Native support.

**Comment by obartra** [comment]
Closing to see if semantic release triggers a release when there's no PR attached to `next`

**Comment by obartra** [comment]
A version of gymnast has been released on the next branch. To try it out, run `yarn gymnast@17.0.0-next.1`

**Pull request merged**
